### ISSUE TITLE
Old link to JobFile Reference

### ISSUE THREAD

**Issue by Mike4Online** [Nuix/Nuix-Collector-Integration#4]
The home page of this GitHub project (i.e. the README) has a link to the JobFile Reference Guide.  This link is for an old version (7.5 or 7.6).  This link should be updated to point to the current JobFile Reference Guide, at the following URL:

https://download.nuix.com/system/files/Nuix%20Collector%20and%20ECC%20JobFile%20Reference%20Guide%20v8.6.pdf

- Michael Litwak (Nuix employee)

**Comment by JuicyDragon** [comment]
Updating now, thank you for reporting this and providing the updated link 😄

**Comment by Mike4Online** [comment]
Thanks for updating the link.  I just realized that the JobFile Reference does not cover remediation-specific elements in the JobFile.  These are intentionally left undocumented in the JobFile Reference, because remediation capabilities are intended to be driven by Workstation.

The Collections Team generates a RemeditionLib library, which allows Workstation to perform remediation.  We have a customized version of the JobFile XML Schema to accompany RemediationLib.  This schema includes a comprehensive set of documentation comments for all possible JobFile elements and attributes, including remediation-related items.  Still, an XML Schema file is not the ideal way to deploy reference documentation.

I am considering writing a supplementary PDF document to cover remediation-related JobFile settings.  I am not sure where I would publish this doc - perhaps having it here in this GitHub repository would be best.  What do you think?

**Comment by JuicyDragon** [comment]
No problem on the link, was a real easy fix.  Thanks for calling it out, I wouldn't have noticed it myself most likely.

Yeah we could definitely include it in the repository.  Seems like it would be an appropriate audience.  Not sure how far reaching you think that would be, but if you feel this is just a supplement for this repo, could even write it up in markdown if you'd like.  I have a little Ruby script that can save it out to rendered HTML with most of the GitHub stuff as you would see it on GitHub.  Could easily turn that into a PDF then.  Whatever format works for you works for me.
________________________________
